name: Hallo Welt mit Kontext

run-name: ${{ github.actor }} hat diesen Workflow ausgelöst

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hallo Welt mit Kontext ausgeben
        run: |
          echo "Hallo, Welt!"
          echo "Ausgelöst von: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Referenz: ${{ github.ref }}"
