name: Hallo Welt mit Issue-Trigger

run-name: ${{ github.actor }} hat diesen Workflow ausgelöst

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Ihr Name für personalisierte Begrüßung'
        required: false
        default: 'World'
        type: string
      greeting:
        description: 'Benutzerdefinierte Begrüßungsnachricht'
        required: false
        default: 'Hello'
        type: string
  issues:
    types: [opened]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Personalisierte Begrüßung ausgeben
        run: |
          echo "$GREETING $NAME!"
          echo "Ausgelöst von: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Referenz: $REF"
        env:
          NAME: ${{ github.event.inputs.name }}
          GREETING: ${{ github.event.inputs.greeting }}
          REF: ${{ github.ref }}
      - name: Issue-Informationen ausgeben
        run: |
          echo "Neues Issue geöffnet!"
          echo "Issue #${{ github.event.issue.number }}: $ISSUE_TITLE"
          echo "Inhalt: $ISSUE_BODY"
          echo "Eröffnet von: ${{ github.event.issue.user.login }}"
          echo "Issue-URL: ${{ github.event.issue.html_url }}"
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
