name: Hello World with Inputs

run-name: ${{ github.actor }} triggered this workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Your name for personalized greeting'
        required: true
        type: string
      greeting:
        description: 'Custom greeting message'
        required: false
        default: 'Hello'
        type: string

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Personalized Greeting
        run: |
          echo "${{ github.event.inputs.greeting }} ${{ github.event.inputs.name }}!"
          echo "Triggered by: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Reference: ${{ github.ref }}"
