name: Hallo Welt mit Eingaben

run-name: ${{ github.actor }} hat diesen Workflow ausgelöst

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Ihr Name für personalisierte Begrüßung'
        required: true
        type: string
      greeting:
        description: 'Benutzerdefinierte Begrüßungsnachricht'
        required: false
        default: 'Hallo'
        type: string

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Personalisierte Begrüßung ausgeben
        run: |
          echo "${{ github.event.inputs.greeting }} ${{ github.event.inputs.name }}!"
          echo "Ausgelöst von: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Referenz: ${{ github.ref }}"
