name: Hallo Welt mit Workflow-Token

run-name: '${{ (github.event.issue && format(''Issue #{0}'', github.event.issue.number)) || (github.event.schedule && ''Cron'') || github.actor }} hat diesen Workflow ausgelöst'

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Ihr Name für personalisierte Begrüßung'
        required: false
        default: 'World'
        type: string
      greeting:
        description: 'Benutzerdefinierte Begrüßungsnachricht'
        required: false
        default: 'Hello'
        type: string
  issues:
    types: [opened]
  schedule:
    - cron: '0 9 * * *'  # Täglich um 9:00 Uhr UTC

permissions:
  contents: read
  actions: read
  issues: write

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub CLI-Authentifizierung prüfen
        run: |
          echo "GitHub CLI-Authentifizierung wird geprüft..."
          gh auth status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Personalisierte Begrüßung ausgeben
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "$GREETING $NAME!"
          echo "Ausgelöst von: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Referenz: $REF"
          echo ""
        env:
          NAME: ${{ github.event.inputs.name }}
          GREETING: ${{ github.event.inputs.greeting }}
          REF: ${{ github.ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Repository-Informationen abrufen
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Repository-Informationen:"
          gh repo view ${{ github.repository }} --json name,owner,description,isPrivate,defaultBranchRef | jq -r '
            "Name: " + .name,
            "Owner: " + .owner.login,  
            "Beschreibung: " + (if .description != "" then .description else "Keine Beschreibung" end),
            "Privat: " + (.isPrivate | tostring),
            "Standard-Branch: " + .defaultBranchRef.name
          '
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Issue-Informationen ausgeben
        if: github.event_name == 'issues'
        run: |
          echo "Neues Issue geöffnet!"
          echo "Issue #${{ github.event.issue.number }}: $ISSUE_TITLE"
          echo "Inhalt: $ISSUE_BODY"
          echo "Eröffnet von: ${{ github.event.issue.user.login }}"
          echo "Issue-URL: ${{ github.event.issue.html_url }}"
          echo ""
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Kommentar zum Issue hinzufügen
        if: github.event_name == 'issues'
        run: |
          gh issue comment ${{ github.event.issue.number }} -R ${{ github.repository }} --body "👋 Hallo! Dieses Issue wurde automatisch von unserem Workflow erkannt. Wir werden es in Kürze prüfen.

          **Issue-Details:**
          - **Titel:** ${{ github.event.issue.title }}
          - **Eröffnet von:** ${{ github.event.issue.user.login }}
          - **Workflow-Lauf:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

          Vielen Dank für das Melden dieses Issues!"
          
          echo "✓ Kommentar zu Issue #${{ github.event.issue.number }} hinzugefügt"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Täglichen Status-Check ausgeben
        if: github.event_name == 'schedule'
        run: |
          echo "Täglicher Status-Check – Alle Systeme betriebsbereit"
          echo "Aktuelle Zeit: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
          echo ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Letzte Workflow-Läufe auflisten
        if: github.event_name == 'schedule'
        run: |
          echo "Letzte Workflow-Läufe:"
          gh run list -R ${{ github.repository }} --limit 5 --json displayTitle,status,conclusion,headBranch | jq -r '.[] | 
            (if .conclusion == "success" then "✓" 
             elif .conclusion == "failure" then "✗" 
             elif .status == "in_progress" then "⏳" 
             else "○" end) + " " + .displayTitle + " - " + .headBranch + " (" + (.conclusion // .status) + ")"'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
