name: 'Release-Tag erstellen'
description: 'Erstellt einen Git-Tag für Release-Deployments mit der GitHub API'
author: 'GitHub Actions Learning'

inputs:
  tag-name:
    description: 'Der Name des zu erstellenden Tags (z.B. v1.0.0)'
    required: true
  commit-sha:
    description: 'Der Commit-SHA, der getaggt werden soll'
    required: true
  tag-message:
    description: 'Benutzerdefinierte Nachricht für den Tag'
    required: false
    default: 'Release-Tag erstellt von GitHub Actions'
  github-token:
    description: 'GitHub-Token für API-Zugriff'
    required: true

outputs:
  tag-sha:
    description: 'Der SHA des erstellten Tag-Objekts'
    value: ${{ steps.create-tag.outputs.tag-sha }}
  tag-url:
    description: 'Die URL des erstellten Tags'
    value: ${{ steps.create-tag.outputs.tag-url }}

runs:
  using: 'composite'
  steps:
    - name: 🔍 Eingaben validieren
      shell: bash
      run: |
        echo "🔍 Eingaben werden validiert..."
        
        if [ -z "${{ inputs.tag-name }}" ]; then
          echo "❌ Fehler: tag-name ist erforderlich"
          exit 1
        fi
        
        if [ -z "${{ inputs.commit-sha }}" ]; then
          echo "❌ Fehler: commit-sha ist erforderlich"
          exit 1
        fi
        
        if [ -z "${{ inputs.github-token }}" ]; then
          echo "❌ Fehler: github-token ist erforderlich"
          exit 1
        fi
        
        echo "✅ Alle Eingaben erfolgreich validiert"
        echo "🏷️ Tag-Name: ${{ inputs.tag-name }}"
        echo "📌 Commit SHA: ${{ inputs.commit-sha }}"
        echo "💬 Tag-Nachricht: ${{ inputs.tag-message }}"

    - name: 🏷️ Release-Tag erstellen
      id: create-tag
      shell: bash
      run: |
        echo "🏷️ Release-Tag wird erstellt: ${{ inputs.tag-name }}"
        
        # Tag-Objekt mit GitHub REST API erstellen
        echo "📝 Tag-Objekt wird erstellt..."
        create_tag_response=$(curl -s -w "%{http_code}" \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.github-token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/git/tags \
          -d @- <<EOF
        {
          "tag": "${{ inputs.tag-name }}",
          "message": "${{ inputs.tag-message }}",
          "object": "${{ inputs.commit-sha }}",
          "type": "commit",
          "tagger": {
            "name": "GitHub Actions",
            "email": "actions@github.com",
            "date": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
          }
        }
        EOF)
        
        # HTTP-Statuscode und Antwort extrahieren
        http_code="${create_tag_response: -3}"
        response_body="${create_tag_response%???}"
        
        if [ "$http_code" -ne 201 ]; then
          echo "❌ Tag-Objekt konnte nicht erstellt werden. HTTP-Status: $http_code"
          echo "Antwort: $response_body"
          exit 1
        fi
        
        # Tag-SHA aus Antwort extrahieren
        TAG_SHA=$(echo "$response_body" | grep '"sha":' | head -n 1 | cut -d '"' -f4)
        
        if [ -z "$TAG_SHA" ]; then
          echo "❌ Tag-SHA konnte nicht aus der Antwort extrahiert werden"
          echo "Antwort: $response_body"
          exit 1
        fi
        
        echo "📌 Tag-Objekt SHA: $TAG_SHA"
        
        # Tag-Referenz erstellen
        echo "🔗 Tag-Referenz wird erstellt..."
        create_ref_response=$(curl -s -w "%{http_code}" \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.github-token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/git/refs \
          -d @- <<EOF
        {
          "ref": "refs/tags/${{ inputs.tag-name }}",
          "sha": "$TAG_SHA"
        }
        EOF)
        
        # HTTP-Statuscode für Referenzerstellung extrahieren
        ref_http_code="${create_ref_response: -3}"
        ref_response_body="${create_ref_response%???}"
        
        if [ "$ref_http_code" -ne 201 ]; then
          echo "❌ Tag-Referenz konnte nicht erstellt werden. HTTP-Status: $ref_http_code"
          echo "Antwort: $ref_response_body"
          exit 1
        fi
        
        # Outputs setzen
        echo "tag-sha=$TAG_SHA" >> $GITHUB_OUTPUT
        echo "tag-url=https://github.com/${{ github.repository }}/releases/tag/${{ inputs.tag-name }}" >> $GITHUB_OUTPUT
        
        echo "✅ Release-Tag ${{ inputs.tag-name }} wurde erfolgreich erstellt"
        echo "🔗 Tag-URL: https://github.com/${{ github.repository }}/releases/tag/${{ inputs.tag-name }}"
