name: Externer Repository-Zugriff

on:
  workflow_dispatch:
    inputs:
      target_repo:
        description: 'Ziel-Repository (Besitzer/Repo-Format)'
        required: true
        default: 'your-org/external-repo-test'
        type: string
      issue_title:
        description: 'Titel für das zu erstellende Issue'
        required: true
        default: 'Test-Issue von Workflow'
        type: string
      issue_body:
        description: 'Inhaltsbeschreibung für das Issue'
        required: true
        default: 'Dieses Issue wurde von einem GitHub Actions-Workflow mit einem GitHub App-Token erstellt.'
        type: string

jobs:
  create-external-issue:
    runs-on: ubuntu-latest
    
    steps:
      - name: GitHub App-Token generieren
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          repositories: ${{ github.event.inputs.target_repo }}
      
      - name: Issue im externen Repository erstellen
        id: create-issue
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          echo "Issue wird im Repository erstellt: ${{ github.event.inputs.target_repo }}"
          echo "Issue-Titel: ${{ github.event.inputs.issue_title }}"
          
          # Issue erstellen und Ausgabe erfassen
          issue_url=$(gh issue create \
            --repo "${{ github.event.inputs.target_repo }}" \
            --title "${{ github.event.inputs.issue_title }}" \
            --body "${{ github.event.inputs.issue_body }}")
          
          if [ $? -eq 0 ] && [ -n "$issue_url" ]; then
            echo "✅ Issue erfolgreich erstellt!"
            echo "issue_url=$issue_url" >> $GITHUB_OUTPUT
          else
            echo "❌ Issue konnte nicht erstellt werden"
            exit 1
          fi