name: External Repository Access

on:
  workflow_dispatch:
    inputs:
      target_repo:
        description: 'Target repository (owner/repo format)'
        required: true
        default: 'your-org/external-repo-test'
        type: string
      issue_title:
        description: 'Title for the issue to create'
        required: true
        default: 'Test issue from workflow'
        type: string
      issue_body:
        description: 'Body content for the issue'
        required: true
        default: 'This issue was created by a GitHub Actions workflow using a GitHub App token.'
        type: string

jobs:
  create-external-issue:
    runs-on: ubuntu-latest
    
    steps:
      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          repositories: ${{ github.event.inputs.target_repo }}
      
      - name: Create issue in external repository
        id: create-issue
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          echo "Creating issue in repository: ${{ github.event.inputs.target_repo }}"
          echo "Issue title: ${{ github.event.inputs.issue_title }}"
          
          # Create the issue and capture the output
          issue_url=$(gh issue create \
            --repo "${{ github.event.inputs.target_repo }}" \
            --title "${{ github.event.inputs.issue_title }}" \
            --body "${{ github.event.inputs.issue_body }}")
          
          if [ $? -eq 0 ] && [ -n "$issue_url" ]; then
            echo "✅ Issue created successfully!"
            echo "issue_url=$issue_url" >> $GITHUB_OUTPUT
          else
            echo "❌ Failed to create issue"
            exit 1
          fi