name: Hallo Welt mit Bedingungen

run-name: '${{ (github.event.issue && format(''Issue #{0}'', github.event.issue.number)) || (github.event.schedule && ''Cron'') || github.actor }} hat diesen Workflow ausgelöst'

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Ihr Name für personalisierte Begrüßung'
        required: false
        default: 'World'
        type: string
      greeting:
        description: 'Benutzerdefinierte Begrüßungsnachricht'
        required: false
        default: 'Hello'
        type: string
  issues:
    types: [opened]
  schedule:
    - cron: '0 9 * * *'  # Täglich um 9:00 Uhr UTC

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Personalisierte Begrüßung ausgeben
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "$GREETING $NAME!"
          echo "Ausgelöst von: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Referenz: $REF"
        env:
          NAME: ${{ github.event.inputs.name }}
          GREETING: ${{ github.event.inputs.greeting }}
          REF: ${{ github.ref }}
      
      - name: Issue-Informationen ausgeben
        if: github.event_name == 'issues' # oder github.event.issue (implizite Nicht-Null-Prüfung)
        run: |
          echo "Neues Issue geöffnet!"
          echo "Issue #${{ github.event.issue.number }}: $ISSUE_TITLE"
          echo "Inhalt: $ISSUE_BODY"
          echo "Eröffnet von: ${{ github.event.issue.user.login }}"
          echo "Issue-URL: ${{ github.event.issue.html_url }}"
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
      
      - name: Täglichen Status-Check ausgeben
        if: github.event_name == 'schedule'
        run: |
          echo "Täglicher Status-Check – Alle Systeme betriebsbereit"
          echo "Aktuelle Zeit: $(date -u +%Y-%m-%dT%H:%M:%SZ)"