name: Full CI/CD Pipeline with Reusable Workflows

run-name: Deployment to ${{ github.event.inputs.environment || 'development' }} triggered by ${{ github.event_name == 'workflow_dispatch' && github.actor || format('push from {0} ({1})', github.event.pusher.name, github.sha) }}

on:
  push:
    branches: [ main ]
    paths-ignore: [ '.github/**' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment for deployment'
        required: true
        type: choice
        options:
          - development
          - production
        default: 'development'

env:
  SOLUTION_PATH: './exercises/09-full-ci-cd-pipeline/sample-app/SampleApp.sln'
  PROJECT_PATH: './exercises/09-full-ci-cd-pipeline/sample-app/SampleApp/SampleApp.csproj'
  TEST_PROJECT_PATH: './exercises/09-full-ci-cd-pipeline/sample-app/SampleApp.Tests/SampleApp.Tests.csproj'

jobs:
  build:
    name: 🔨 Build Application
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        dotnet-version: ['8.0.x', '9.0.x']
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
      
      - name: 🔧 Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      
      - name: 📦 Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_PATH }}
      
      - name: 🔨 Build application
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

      - name: 🧪 Run unit tests
        run: |
          dotnet test ${{ env.TEST_PROJECT_PATH }} \
            --configuration Release \
            --logger "trx;LogFileName=test-results.trx" \
            --collect:"XPlat Code Coverage" \
            --results-directory TestResults/
      
      - name: 📊 Publish test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.dotnet-version }}
          path: TestResults/
          retention-days: 1
      
      - name: 📈 Display test summary
        if: always()
        run: |
          echo "🧪 Test Results Summary for .NET ${{ matrix.dotnet-version }}"
          echo "Test files located in TestResults directory"
          find TestResults -name "*.trx" -exec echo "Found test result file: {}" \;
      
      - name: 📤 Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.dotnet-version }}
          path: |
            exercises/09-full-ci-cd-pipeline/sample-app/SampleApp/bin/Release/
            exercises/09-full-ci-cd-pipeline/sample-app/SampleApp.Tests/bin/Release/
          retention-days: 1

  package:
    name: 📦 Package Application
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
      
      - name: 🔧 Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: 📦 Publish application
        run: |
          dotnet publish ${{ env.PROJECT_PATH }} \
            --configuration Release \
            --output ./publish \
            --self-contained false
      
      - name: 📋 Create deployment package
        run: |
          # Create version info
          echo "Build Information" > ./publish/build-info.txt
          echo "==================" >> ./publish/build-info.txt
          echo "Build Date: $(date)" >> ./publish/build-info.txt
          echo "Commit SHA: ${{ github.sha }}" >> ./publish/build-info.txt
          echo "Branch: ${{ github.ref_name }}" >> ./publish/build-info.txt
          echo "Actor: ${{ github.actor }}" >> ./publish/build-info.txt
          echo "Workflow: ${{ github.workflow }}" >> ./publish/build-info.txt
      
      - name: 📤 Upload deployment package
        uses: actions/upload-artifact@v4
        with:
          name: deployment-package
          path: ./publish/
          retention-days: 30

  deploy-dev:
    name: 🚀 Deploy to Development
    uses: ./.github/workflows/reusable-deploy.yml
    needs: package
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
    with:
      environment: ${{ github.event.inputs.environment || 'development' }}
      package-name: 'deployment-package'
      app-url: 'https://dev-sampleapp.example.com'
      is-production: false
    secrets: inherit

  deploy-prod:
    name: 🏭 Deploy to Production
    uses: ./.github/workflows/reusable-deploy.yml
    needs: deploy-dev
    if: github.ref == 'refs/heads/main' && github.event.inputs.environment == 'production'
    permissions:
      contents: write
    with:
      environment: 'production'
      package-name: 'deployment-package'
      app-url: 'https://sampleapp.example.com'
      is-production: true
    secrets: inherit

  notify:
    name: 📢 Notify Deployment Status
    runs-on: ubuntu-latest
    needs: [ deploy-dev, deploy-prod ]
    if: always() && (needs.deploy-dev.result != 'skipped' || needs.deploy-prod.result != 'skipped')
    
    steps:
      - name: 📢 Send notification
        run: |
          echo "📧 Sending deployment notifications..."
          
          # Development notification
          if [ "${{ needs.deploy-dev.result }}" != 'skipped' ]; then
            if [ ${{ needs.deploy-dev.outputs.deployment-status }} ]; then
              echo "✅ Development deployment successful"
            else
              echo "❌ Development deployment failed"
            fi
          else
            echo "🚫 Development deployment skipped"
          fi
          
          # Production notification
          if [ "${{ needs.deploy-prod.result }}" != 'skipped' ]; then
            if [ ${{ needs.deploy-prod.outputs.deployment-status }} ]; then
              echo "✅ Production deployment successful"
            else
              echo "❌ Production deployment failed"
            fi
          else
            echo "🚫 Production deployment skipped"
          fi
          
          echo "📊 Deployment completed at $(date)"